#!/bin/bash
set -eux
set -o pipefail

pep8_options=(
    --show-source
)

pylint_options=(
    --disable=invalid-name  # TODO don't ignore
    --disable=line-too-long  # TODO don't ignore
    --disable=missing-docstring
    --disable=star-args
    --include-naming-hint=yes
    --output-format=colorized
    --reports=no
)

find . -name '*.py' | xargs pep8 ${pep8_options[*]}

py2files=()
py3files=()
for pyfile in *.py; do
    if head -n 1 "$pyfile" | grep python3; then
        py3files[${#py3files[@]}]="$pyfile"
    else
        py2files[${#py2files[@]}]="$pyfile"
    fi
done

if [[ ${#py2files[@]} != 0 ]]; then
    pylint "${pylint_options[@]}" "${py2files[@]}"
fi
if [[ ${#py3files[@]} != 0 ]]; then
    pylint3 "${pylint_options[@]}" "${py3files[@]}"
fi

py.test-3

echo OK
